require('dotenv').config();

const path = require('path');
const express = require('express');
const { createClient } = require('@supabase/supabase-js');

const EmailService = require('./server/emailService');

const app = express();
const PORT = process.env.PORT || 3000;
const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD;
const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!ADMIN_PASSWORD) {
    console.error('ADMIN_PASSWORD environment variable is required. Exiting.');
    process.exit(1);
}

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    console.error('SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY are required. Exiting.');
    process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
        persistSession: false
    },
    global: {
        fetch
    }
});

const ensureSchema = async () => {
    const { error } = await supabase
        .from('applications')
        .select('id')
        .limit(1);
    if (!error) return;
    if (error.code && error.code !== '42P01') {
        throw error;
    }

    const ddl = `
        create table if not exists public.applications (
            id bigint generated by default as identity primary key,
            email text not null,
            company text not null,
            comment text,
            created_at timestamptz not null default now()
        );
    `;

    const rpcUrl = new URL('/rest/v1/rpc/exec_sql', SUPABASE_URL).toString();

    const response = await fetch(rpcUrl, {
        method: 'POST',
        headers: {
            apikey: SUPABASE_SERVICE_ROLE_KEY,
            Authorization: `Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({ sql: ddl })
    });

    if (!response.ok) {
        const body = await response.text();
        const ddlError = new Error(`Failed to ensure applications table: ${body}`);
        ddlError.status = response.status;
        throw ddlError;
    }
};

const emailService = new EmailService({
    from: process.env.MAIL_FROM || 'MB3R Lab <noreply@mb3r-lab.org>',
    apiKey: process.env.MAILGUN_API_KEY,
    domain: process.env.MAILGUN_DOMAIN,
    baseUrl: process.env.MAILGUN_API_BASE_URL
});

const isValidEmail = (value = '') => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim());

app.use(express.json());

app.use('/assets', express.static(path.join(__dirname, 'assets')));

['manifest.webmanifest', 'robots.txt', 'sitemap.xml'].forEach((fileName) => {
    app.get(`/${fileName}`, (_, res) => {
        res.sendFile(path.join(__dirname, fileName));
    });
});

const sendIndex = (_, res) => res.sendFile(path.join(__dirname, 'index.html'));
const sendAdmin = (_, res) => res.sendFile(path.join(__dirname, 'admin.html'));

app.get('/', sendIndex);
app.get('/index.html', sendIndex);
app.get('/admin', sendAdmin);

app.post('/api/applications', async (req, res, next) => {
    try {
        const { email, company, comment } = req.body || {};
        const normalizedEmail = email ? String(email).trim().toLowerCase() : '';
        const normalizedCompany = company ? String(company).trim() : '';
        const normalizedComment = comment ? String(comment).trim() : null;

        if (!normalizedEmail || !isValidEmail(normalizedEmail)) {
            return res.status(400).json({ message: 'Please provide a valid email address.' });
        }

        if (!normalizedCompany) {
            return res.status(400).json({ message: 'Company is required.' });
        }

        const { data, error } = await supabase
            .from('applications')
            .insert({
                email: normalizedEmail,
                company: normalizedCompany,
                comment: normalizedComment
            })
            .select('id')
            .single();

        if (error) {
            throw error;
        }

        try {
            await emailService.sendConfirmation(normalizedEmail, normalizedCompany);
        } catch (emailError) {
            console.error('[email] Unable to send confirmation:', emailError);
        }

        return res.status(201).json({
            id: data?.id,
            message: 'Request received.'
        });
    } catch (error) {
        return next(error);
    }
});

app.get('/api/applications', async (req, res) => {
    const providedPassword = req.header('x-admin-pass');

    if (!providedPassword) {
        return res.status(401).json({ message: 'Administrator password required.' });
    }

    if (providedPassword !== ADMIN_PASSWORD) {
        return res.status(403).json({ message: 'Incorrect password.' });
    }

    try {
        const { data, error } = await supabase
            .from('applications')
            .select('id, email, company, comment, created_at')
            .order('created_at', { ascending: false });

        if (error) {
            throw error;
        }

        return res.json(data);
    } catch (error) {
        console.error('[supabase] Failed to fetch applications:', error);
        return res.status(500).json({ message: 'Unable to load applications.' });
    }
});

app.use((_, res) => {
    res.status(404).json({ message: 'Not found' });
});

app.use((err, req, res, _next) => {
    console.error(err);
    res.status(500).json({ message: 'Internal server error.' });
});

ensureSchema()
    .then(() => {
        app.listen(PORT, () => {
            console.log(`MB3R Lab server listening on http://localhost:${PORT}`);
        });
    })
    .catch((schemaError) => {
        console.error('Failed to initialize schema:', schemaError);
        process.exit(1);
    });

module.exports = app;
